version: 2
jobs:
  test:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Install NPM modules
          command: npm install
      - run:
          name: Run test
          command: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
