version: 2
jobs:
  test:
    docker:
      - image: node:6
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - run:
          name: Run test
          command: yarn test

      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
